USE [master]
GO

/****** Object:  Database [DW_ventass]    Script Date: 28/7/2026 16:26:36 ******/
CREATE DATABASE [DW_ventass]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'DW_ventass', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DW_ventass.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'DW_ventass_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\DW_ventass_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [DW_ventass].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [DW_ventass] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [DW_ventass] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [DW_ventass] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [DW_ventass] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [DW_ventass] SET ARITHABORT OFF 
GO

ALTER DATABASE [DW_ventass] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [DW_ventass] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [DW_ventass] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [DW_ventass] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [DW_ventass] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [DW_ventass] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [DW_ventass] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [DW_ventass] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [DW_ventass] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [DW_ventass] SET  ENABLE_BROKER 
GO

ALTER DATABASE [DW_ventass] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [DW_ventass] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [DW_ventass] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [DW_ventass] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [DW_ventass] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [DW_ventass] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [DW_ventass] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [DW_ventass] SET RECOVERY FULL 
GO

ALTER DATABASE [DW_ventass] SET  MULTI_USER 
GO

ALTER DATABASE [DW_ventass] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [DW_ventass] SET DB_CHAINING OFF 
GO

ALTER DATABASE [DW_ventass] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [DW_ventass] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [DW_ventass] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [DW_ventass] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [DW_ventass] SET QUERY_STORE = ON
GO

ALTER DATABASE [DW_ventass] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

ALTER DATABASE [DW_ventass] SET  READ_WRITE 
GO

